# .github/workflows/test.yml
name: Run Tests

on:
  push:
    branches:
      - main # Change this if you want to target a different branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Create results directory
        run: mkdir -p test-results # Create the directory if it doesn't exist

      - name: Run tests and generate results
        run: npm test -- --reporter=json > test-results/results.json

      - name: List test results
        run: ls -R test-results

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/**/*
